[features]
seeds = false
[programs.localnet]
solana_twitter = "FTyY4YaXqAPh5mt8QLEAzr9xWv4FBnnveSRK5p6oxZfZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
